export enum Button {
	UP = "UP",
	DOWN = "DOWN",
	LEFT = "LEFT",
	RIGHT = "RIGHT",
	SUBMIT = "SUBMIT",
	ACTION = "ACTION",
	CANCEL = "CANCEL",
	MENU = "MENU",
	STATS = "STATS",
	CYCLE_SHINY = "CYCLE_SHINY",
	CYCLE_FORM = "CYCLE_FORM",
	CYCLE_GENDER = "CYCLE_GENDER",
	V = "V",
	SPEED_UP = "SPEED_UP",
	SLOW_DOWN = "SLOW_DOWN"
}
