export enum Challenges {
    SINGLE_TYPE = "SINGLE_TYPE",
    LOWER_MAX_STARTER_COST = "LOWER_MAX_STARTER_COST",
    LOWER_STARTER_POINTS = "LOWER_STARTER_POINTS",
    FRESH_START = "FRESH_START",
    INVERSE_BATTLE = "INVERSE_BATTLE",
}
