export enum PokeballType {
  POKEBALL = "POKEBALL",
  GREAT_BALL = "GREAT_BALL",
  ULTRA_BALL = "ULTRA_BALL",
  ROGUE_BALL = "ROGUE_BALL",
  MASTER_BALL = "MASTER_BALL",
  LUXURY_BALL = "LUXURY_BALL",
}
